
#GET http://localhost:8080/api/admin/users

#
#GET http://localhost:8080/api/admin/2

#
POST http://localhost:8080/api/admin/add
Content-Type: application/json

{
  "firstName": "Roman",
  "lastName": "Sayapin",
  "email": "roma@mail.ru",
  "password": "103",
  "roles": [{
    "role": "USER"
  }]
}

#PUT http://localhost:8080/api/admin/update
#Content-Type: application/json
#
#{
#  "id": 1,
#  "firstName": "Tony",
#  "lastName": "Stark",
#  "email": "tonySt@gmai.com",
#  "password": "100",
#  "roles": [
#    {
#      "id": 1,
#      "role": "ADMIN"
#    }
#  ]
#}

#DELETE http://localhost:8080/api/admin/4